# Generated by Django 4.2.1 on 2023-05-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='codemeli',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='person',
            name='number',
            field=models.IntegerField(),
        ),
    ]
